install package.xml for 'emulator' with correct 'Pkg.Path'
The 'emulator' package only has a single install dir, it is not versioned.
fdroid/sdkmanager allows specifying the version, but it should still
install into the canonical dir layout.  This is required for avdmanager to
find the installed emulator.

$ avdmanager create avd --name avd_23_default_x86_64 --tag default --package "system-images;android-23;default;x86_64" --sdcard 64M --device "Nexus 5"
Warning: Observed package id 'emulator;30.3.5' in inconsistent location '/opt/android-sdk/emulator' (Expected '/opt/android-sdk/emulator/30.3.5')
Auto-selecting single ABI x86_64========] 100% Fetch remote repository...
Error: "emulator" package must be installed!
null